export const OPEN_DIRECTORY = 'OPEN_DIRECTORY';
export const OPEN_FILE = 'OPEN_FILE';
export const SHOW_MESSAGE_BOX = 'SHOW_MESSAGE_BOX';

export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const OPEN_LOG_FILE = 'OPEN_LOG_FILE';
export const OPEN_SETTINGS_FILE = 'OPEN_SETTINGS_FILE';

export const IMPORT_DATA = 'IMPORT_DATA';
export const EXPORT_DATA = 'EXPORT_DATA';

export const READ_GATES = 'READ_GATES';
export const READ_GATE = 'READ_GATE';
export const CREATE_GATE = 'CREATE_GATE';
export const UPDATE_GATE = 'UPDATE_GATE';
export const DELETE_GATE = 'DELETE_GATE';

export const READ_STRUCTURE_DECKS = 'READ_STRUCTURE_DECKS';
export const READ_STRUCTURE_DECK = 'READ_STRUCTURE_DECK';
export const CREATE_STRUCTURE_DECK = 'CREATE_STRUCTURE_DECK';
export const UPDATE_STRUCTURE_DECK = 'UPDATE_STRUCTURE_DECK';
export const DELETE_STRUCTURE_DECK = 'DELETE_STRUCTURE_DECK';

export const IMPORT_DECK = 'IMPORT_DECK';
export const EXPORT_DECK = 'EXPORT_DECK';
